server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
   driver-class-name: org.postgresql.Driver
   url: postgres://voeuszywtqzcrc:b4a6ac740da99b63e145a7d27b02bccf0bd3029b237b1db095fde1eacd4037e6@ec2-3-212-75-25.compute-1.amazonaws.com:5432/d5ufkpm84ft1m2
   username: voeuszywtqzcrc
   password: b4a6ac740da99b63e145a7d27b02bccf0bd3029b237b1db095fde1eacd4037e6
  jpa:
   show-sql: true
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   generate-ddl: true
   hibernate: 
     ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend
  version: 1.0